services:
  db:
    image: postgis/postgis:16-3.4
    container_name: sniffies_clone_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: